base_path : '/iap/6.828/'
production_url : 'https://sipb.mit.edu/iap/6.828/'

pages :
  permalink: '/:relative_path/:filename'
  sort: ['position', 'asc']
  paginator:
    enable: false
  rss:
    enable: false

lab:
  paginator:
    enable: false
  rss:
    enable: false

_root:
  paginator:
    enable: false
  rss:
    enable: false

files :
  use: static
  paginator:
    enable: false
  rss:
    enable: false

readings :
  use: static
  paginator:
    enable: false
  rss:
    enable: false

widgets :
  syntax :
    use : prettify
    linenums : false
    cdn : false
